spring:
  datasource:
    url: jdbc:log4jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres

    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: postgres.whkezjayfofphnlenvdw
    password: kmw1871020679
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect #org.hibernate.dialect.H2Dialect

logging:
  level:
    back.cmm.module: debug
