spring:
  datasource:
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: postgres
    password: 1871020679
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect #org.hibernate.dialect.H2Dialect

logging:
  level:
    back.cmm.module: debug
