spring:

  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 5120MB

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

jwt:
  header: Authorization
  secret: luZsdmVybm0LWp3ZWNoLXNwcmlc2lS10ZWNyZXQtc2lsdmVybmuZy1ib290LWp3dCluZS10ZWNoLXNwcmluZy1ib2910dXRvcmlhbC1zdC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 28_800 # (60 * 60) * 8 = 28,800 (8시간)

