spring:
  datasource:
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: postgres
    password: 22911270
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
logging:
  level:
    back.cmm.module: debug
