spring:

  profiles:
    active: superbase

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 5120MB

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

#  가장 하단 " rest-api " 으로 대체해서 사용중 ..
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: 1b958d55ee701ac4832129d0dc1ae757
#            client-secret: PcBSPdiVElgdYAt9tqmMvMJbjooKwl7i
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://localhost:8080/ouath/test"
#            scope: account_email
#
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id

jwt:
  header: Authorization
  secret: luZsdmVybm0LWp3ZWNoLXNwcmlc2lS10ZWNyZXQtc2lsdmVybmuZy1ib290LWp3dCluZS10ZWNoLXNwcmluZy1ib2910dXRvcmlhbC1zdC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 28_800 # (60 * 60) * 8 = 28,800 (8시간)

rest-api:
  oauth2:
    login-code:
      kakao:
        client-id: 1b958d55ee701ac4832129d0dc1ae757
        client-secret: PcBSPdiVElgdYAt9tqmMvMJbjooKwl7i
        authorization-grant-type: authorization_code
        redirect-uri: "http://localhost:8080/ouath/test"
        scope: account_email

    access-token:
      kakao:
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        user-name-attribute: id
      google:
        client-id: 648648052301-9n52bears5e77ia30tmedrr6s7no1s86.apps.googleusercontent.com
        client-secret: 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
        authorization-grant-type: authorization_code
        redirect-uri: http://localhost:3000/oauth-login/google
        scope: profile